watercoolerproject/watercoolerapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'watercooler'

urlpatterns=[
	path('login/', auth_views.login, name='login'),
	path('logout/', auth_views.logout, {'next_page':'/'}, name='logout'),
	path('signup/', views.signup, name='register'),
	path('signup2/', views.signup2, name='signup2'),
	path('feed/', views.feed, name='feed'),
	path('', views.index, name='index'),
]

watercoolerproject/watercoolerproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('watercoolerapp.urls')),
    path('admin/', admin.site.urls),
]

watercoolerproject/watercoolerapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_no = models.IntegerField(blank=True, null=True)
    #company = models.ForeignKey(Company, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    anniversary_date = models.DateField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to=None,height_field=None,width_field=None)

class Post(models.Model):
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	content = models.TextField(max_length=200, null=True, blank=True)
	published_date = models.DateTimeField(auto_now=True)
	image = models.ImageField(null=True, blank=True)

class Like(models.Model):
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

#class Company(models.Model):
	#company_name = models.CharField(max_length=30, blank=False, null=False)

watercoolerproject/watercoolerapp/forms.py
from django import forms
from .models import Profile, Post, Like

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('mobile_no', 'anniversary_date', 'birth_date')		

class PostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields = ('content', 'image')

class LikeForm(forms.ModelForm):
	class Meta:
		model=Like
		fields = ()

watercoolerproject/watercoolerapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import UserProfileForm, PostForm, LikeForm
from django.contrib.auth import authenticate, login
from django.views import generic
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from .models import Post, Like

def index(request):
    if request.user.is_authenticated:
    	return redirect('watercooler:feed')
    else:
    	return render(request, 'watercooler/index.html')    	

def feed(request):
	if request.user.is_authenticated:
		posts = Post.objects.order_by('-published_date')
		if request.method=='POST':
			if 'Like' in request.POST:
				form = LikeForm(request.POST)
				if form.is_valid():
					data=form.save(commit=False)
					data.author = request.user
					data.save()
			else:
				form = PostForm(request.POST)
				if form.is_valid():
					data=form.save(commit=False)
					data.author = request.user
					data.save()
	else:
		return render(request, 'watercooler/index.html')
	return render(request, 'watercooler/feed.html', {'postlist':posts, 'userlist':User.objects.all()})


def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('watercooler:signup2')
	else:
		form = UserCreationForm()
	return render(request, 'watercooler/signup.html', {'form':form})

def signup2(request):
	if request.method == 'POST':
		form = UserProfileForm(request.POST)
		if form.is_valid():
			profile=form.save(commit=False)
			profile.user=request.user
			profile.save()
			return redirect('watercooler:index')
	else:
		form = UserProfileForm()
	return render(request, 'watercooler/signup2.html',{'form':form})

watercoolerproject/watercoolerapp/templates/watercooler/feed.html
{% extends 'watercooler/home.html' %}

{% block body %}
<div class="container">
	<div class="post_idea tab">
		<button class="tablinks" onclick="openCity(event, 'Make a post')"><span><i class="fas fa-pen"></i></span>Make a post</button>
		<button class="tablinks" onclick="openCity(event, 'Photo/Video')"><span><i class="far fa-images"></i></span>Photo/Video</button>
		<form method="POST">
		{% csrf_token %}
		<button class="button_post" type="submit">Post</button>
		<div id="Make a post" class="tabcontent">
			<textarea rows="5" cols="50" placeholder="Write Something Here...." name="content"></textarea>
		</div>
		<div id="Photo/Video" class="tabcontent">
			<span>Caption:<input type="text" name="caption"></span>
			<span>Upload Image<input type="file" name="image"></span>
		</div>
		</form>
	</div>
</div>
{% for post in postlist %}
	<div class="POSTS">
		<h3>{{ post.author }}</h3>
		<h5>{{ post.content }}</h5>
		{% if post.image %}
		<img src="{{ post.image.url }}"/>
		{% endif %}
		<div class="row react">
			<p class="col" id="Like"><span><i class="fa fa-star"> </i> </span>  LIKE</p>

		</div>
		</form>
	</div>
{% endfor %}
{% endblock %}

watercoolerproject/watercoolerapp/templates/watercooler/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>WELCOME TO YOUR PROFILE!</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'home.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>	
<body>
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand HEAD" href="#"><i class="far fa-laugh-beam"></i>TheWaterCooler</a>
       <input type="text" name="search" placeholder="   Search here" id="search">
       <button><i class="fas fa-search"></i></button>
       </div>
       <a href="{% url 'watercooler:logout' %}" type="button" id="LogoutButton">Logout</a>
    </div>
       <!-- <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
    </ul> -->
   <!--  <ul class="nav navbar-nav navbar-right">
    	<li><div>
      <button>Sign Up</button>
      <button>Login</button>
  </div></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul> -->
</nav>
	  	<div class="row bodyrow">
		<div class="col-sm-3 col-md-2 fields">
			<p></p>
			<p></p>
			<p></p>
			<p></p>
			<p id="water"><h4><strong>The Water Cooler</strong></h4></p>
			<p></p>
			<p>
				<i class="fas fa-laptop"></i>   Computers
			</p>
			<p>
				<i class="fas fa-globe"></i>    IT
			</p>
			<p>
				<i class="fas fa-car-alt"></i>   Mechanical
			</p>
			<p>
				<i class="fas fa-bolt"></i>    EXTC
			</p>

		</div>
		<div class="col-sm-5 col-md-7 main">
			{% block body %}
			{% endblock %}
		</div>
		<div class="right_fields col-sm-3 col-md-2">
			<h4>The Coworker Central</h4>
			<br>
			{% for x in userlist %}
				<p>{{ x.username }}</p>
			{% endfor %}
		</div>
	</div>

<script src="{% static 'mainfeed.js' %}"></script>

</body>
</html>

watercoolerproject/watercoolerapp/templates/watercooler/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Water Cooler</title>
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<div class="heading">
  <h1>The Water Cooler</h1>
  <h2>Collaborate. Connect. Cherish</h2>
</div>

<div class="form">
  <div class="tab">
    <a href="{% url 'watercooler:login' %}" type="button">Login</a>
    <a href="{% url 'watercooler:register' %}" type="button">Register</a>

</div>

<div class="container" id="forms">
  {% block body %}

  {% endblock %}
</div>
</body>
</html> 

watercoolerproject/watercoolerapp/templates/watercooler/next.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="POST" action="{% url 'watercoolerapp:signupformview' %}">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="submit">
	</form>
</body>
</html>

watercoolerproject/watercoolerapp/templates/watercooler/signup.html
{% extends 'watercooler/index.html' %}

{% block body %}  
  <form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="Next" label="Next">
	</form>
{% endblock %}

watercoolerproject/watercoolerapp/templates/watercooler/signup2.html
{% extends 'watercooler/index.html' %}

{% block body %} 
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="Submit">
	</form>
{% endblock %}